"""
Django settings for usea project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Environment-based configuration
ENVIRONMENT = config('environment', default='development')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
if ENVIRONMENT == 'production':
    DEBUG = False
else:
    DEBUG = config('DEBUG', default=True, cast=bool)

# Environment-specific allowed hosts
if ENVIRONMENT == 'production':
    # Production: specific domains only
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]
else:
    # Development: localhost
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'advance',
    'attendance',
    'dashboard',
    'employee',
    'expense',
    'payroll',
    'project',
    'revenue',
    'user',

    

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.AllowOptionsMiddleware',
    'core.middleware.RefreshTokenMiddleware',
    'core.api_logging.APILoggingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'analytics.middleware.TrackAnonymousVisitorMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'construction_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'construction_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Development: SQLite for simplicity
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'user.validators.StrongPasswordValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Environment-specific static files settings
if ENVIRONMENT == 'production':
    # Production: Serve static files from whitenoise or similar
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    # Additional production static file settings can be added here
else:
    # Development: No additional static files configuration needed
    pass

# File upload security settings
# These settings apply to all file uploads in the application
if ENVIRONMENT == 'production':
    # Production: Strict file upload limits
    DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB max for in-memory uploads
    FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB max for file uploads
    DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000  # Limit number of form fields
else:
    # Development: More lenient limits for testing
    DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB max for in-memory uploads
    FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB max for file uploads
    DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000  # Limit number of form fields

# Additional file upload security
FILE_UPLOAD_PERMISSIONS = 0o644  # Restrictive permissions for uploaded files
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755  # Restrictive permissions for upload directories

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'user.User'

# Rest framework
REST_FRAMEWORK={
    'NON_FIELD_ERRORS_KEY':'error',
        'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',

    ),
    "DEFAULT_FILTER_BACKENDS": [
    "django_filters.rest_framework.DjangoFilterBackend",
    "rest_framework.filters.SearchFilter",
    "rest_framework.filters.OrderingFilter",
    ],
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],

    # Rate limiting configuration - environment specific
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'core.throttling.StrictAnonRateThrottle',
    #     'core.throttling.StrictUserRateThrottle',
    # ],
    # # Throttle rates - will be overridden by environment below
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '500/hour',
    #     'user': '2000/hour',
    #     'login': '5/min',
    #     'password_reset': '10/hour',
    #     'burst': '60/min',
    #     'data_modification': '200/minute',
    #     'upload': '30/minute',
    # },
}

# Environment-specific throttle rate overrides
# if ENVIRONMENT == 'production':
#     # Production: Strict rate limiting
#     REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
#         'anon': '100/hour',
#         'user': '1000/hour',
#         'password_reset': '3/hour',
#         'burst': '20/min',
#         'data_modification': '100/minute',
#         'upload': '10/minute',
#     }
# else:
#     # Development: More lenient rate limiting for testing
#     REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
#         'anon': '1000/hour',
#         'user': '5000/hour',
#         'password_reset': '30/hour',
#         'burst': '120/min',
#         'data_modification': '500/minute',
#         'upload': '60/minute',
#     }

from datetime import timedelta

# JWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}


# Security settings for CORS and cookies - environment specific
if ENVIRONMENT == 'production':
    # Production: Strict security settings
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    CORS_ALLOW_CREDENTIALS = True
    SESSION_COOKIE_SAMESITE = 'Strict'
    CSRF_COOKIE_SAMESITE = 'Strict'

    # Additional production security settings
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
else:
    # Development: More permissive for local development
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    CORS_ALLOW_CREDENTIALS = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

    # Development: Disable additional security for easier local development
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Only allow specific origins for CORS requests
# Support both single and multiple origins from environment variable
frontend_url = config('FRONTEND_URL', default="http://localhost:8080")

if ENVIRONMENT == 'production':
    # Production: Require explicit CORS origins
    additional_origins = config('CORS_ALLOWED_ORIGINS', default="")
    if additional_origins:
        origins = [origin.strip() for origin in additional_origins.split(',') if origin.strip()]
        origins.append(frontend_url)
        CORS_ALLOWED_ORIGINS = list(set(origins))  # Remove duplicates
    else:
        CORS_ALLOWED_ORIGINS = [frontend_url]
else:
    # Development: Allow localhost for easier development
    additional_origins = config('CORS_ALLOWED_ORIGINS', default="")
    if additional_origins:
        origins = [origin.strip() for origin in additional_origins.split(',') if origin.strip()]
        origins.extend(['http://localhost:8080', 'http://127.0.0.1:8080'])
        CORS_ALLOWED_ORIGINS = list(set(origins))
    else:
        CORS_ALLOWED_ORIGINS = ['http://localhost:8080', 'http://127.0.0.1:8080']

# Additional CORS security settings
CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'x-csrftoken',
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

# Email settings for sending emails using Gmail's SMTP server. The configuration includes the email backend, host, port, TLS usage, and credentials for the email account. This setup allows the Django application to send emails for various purposes, such as user registration, password resets, or notifications.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# for log files of errors and information
from core.api_logging import SimpleColoredFormatter

LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

# Set up logging configuration with console and file handlers, using a custom colored formatter for console output and a verbose formatter for log files. Logs are stored in the "logs" directory, with errors logged to "errors.log". The logging configuration is designed to capture both informational messages and errors from the Django application, with specific loggers for the Django framework and the user app.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple_colored": {
            "()": SimpleColoredFormatter,
        },
        "verbose": {  # For log files
            "format": "[{asctime}] {levelname} [{name}:{lineno}] {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple_colored",  # Terminal output
        },
        "error_file": {
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "errors.log"),
            "formatter": "verbose",
            "level": "ERROR",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "error_file"],
            "level": "INFO",
            "propagate": True,
        },
        "user": {
            "handlers": ["console", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# Optional — don't expire when the browser closes
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# cache settings for user details, using file-based caching
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": "/home/meow/django_cache",  # folder to store cache files
        "TIMEOUT": 60 * 5,  # default cache timeout (5 minutes)
        "OPTIONS": {
            "MAX_ENTRIES": 1000
        }
    }
}