# Generated by Django 5.2.8 on 2026-04-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.CharField(blank=True, help_text='Initials for avatar display', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Mason', 'Mason'), ('Labor', 'Labor'), ('Engineering', 'Engineering'), ('Product', 'Product'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('HR', 'HR')], default='Labor', max_length=20),
        ),
    ]
