# Generated by Django 5.2.8 on 2026-04-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_avatar_employee_email_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Mason', 'Mason'), ('Labor', 'Labor')], default='Labor', max_length=20),
        ),
    ]
