# Generated by Django 5.2.8 on 2026-05-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_paid_date',
            field=models.DateField(blank=True, help_text='Last date wages were paid out', null=True),
        ),
    ]
