# Generated by Django 5.2.8 on 2026-04-19 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('client_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pay_method', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Check', 'Check')], default='Cash', max_length=20)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='project.project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
