# Generated by Django 5.2.8 on 2026-05-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
