# Generated by Django 5.2.8 on 2026-05-10 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0001_initial'),
        ('employee', '0004_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('payment_type', models.CharField(choices=[('wage', 'Wage Payment'), ('advance', 'Advance Payment')], default='wage', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('days_paid', models.IntegerField(default=0, help_text='Number of days this payment covers')),
                ('start_date', models.DateField(help_text='Start date of the period this payment covers')),
                ('end_date', models.DateField(help_text='End date of the period this payment covers')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='employee.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
