# Generated by Django 5.2.8 on 2026-05-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0002_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
