# Generated by Django 5.2.8 on 2026-04-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Materials', 'Materials'), ('Labor', 'Labor'), ('Equipment', 'Equipment'), ('Advance', 'Advance'), ('Other', 'Other')], default='Materials', max_length=20),
        ),
    ]
