# Generated by Django 5.2.8 on 2026-05-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Materials', 'Materials'), ('Labor', 'Labor'), ('Equipment', 'Equipment'), ('Advance', 'Advance'), ('Payment', 'Payment'), ('Other', 'Other')], default='Materials', max_length=20),
        ),
    ]
