# Generated by Django 5.2.8 on 2026-05-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contract_value',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
    ]
