# Generated by Django 5.2.8 on 2026-04-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_check_in_time_attendance_check_out_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
    ]
