# Generated by Django 5.2.8 on 2026-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Absent', 'Absent')], max_length=10),
        ),
    ]
