name: Deploy to PythonAnywhere
on:
  push:
    branches: [ main ]  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Reload PythonAnywhere Web App
        uses: jensvog/pythonanywhere-webapp-reload-action@v1
        with:
          host: 'www.pythonanywhere.com'  # or 'eu.pythonanywhere.com' for EU servers
          username: 'yakshasoft'
          api-token: '1454c5738a1379e60612bf44f5ae17fcfd8b7040'
          domain-name: 'https://yakshasoft.pythonanywhere.com'