name: Deploy to PythonAnywhere
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest code on PythonAnywhere
        run: |
          curl -s -X POST \
            --data "bash_command=cd /home/yakshasoft/construction_management_server && git pull origin main" \
            -H "Authorization: Token 1454c5738a1379e60612bf44f5ae17fcfd8b7040" \
            https://www.pythonanywhere.com/api/v0/user/yakshasoft/consoles/

      - name: Reload PythonAnywhere Web App
        uses: jensvog/pythonanywhere-webapp-reload-action@v1
        with:
          host: 'www.pythonanywhere.com'
          username: 'yakshasoft'
          api-token: 1454c5738a1379e60612bf44f5ae17fcfd8b7040
          domain-name: 'yakshasoft.pythonanywhere.com'